# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-31 22:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=20)),
                ('result', models.IntegerField(max_length=20)),
                ('difficulty', models.IntegerField(max_length=20)),
            ],
        ),
    ]
